spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xiaozhi?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  liquibase:
    enabled: true
  devtools:
    restart:
      enabled: true
logging:
  level:
    com.xiaozhi: warn
